#!/bin/sh

yel='\033[33m'
pur='\033[35m'
gre='\033[32m'
rst='\033[0m'

pipe="${pur}|${rst}"

while true; do
	CPU_SPEED=$(sysctl hw.cpuspeed | cut -d "=" -f 2 | cut -d "." -f 1)
	CPU_TEMP=$(sysctl hw.sensors.cpu0.temp0 | cut -d "=" -f 2 | cut -d "." -f 1)
	RAM=$(top | grep Memory | awk {'print $6'})
	BAT_STATUS=$(sysctl hw.sensors.acpiac0.indicator0 | cut -d "=" -f 2 | cut -d "." -f 1)
	BAT=$(apm -l)
	DATE=$(date +"%B %d - %H:%M")
	SSID=$(ifconfig | grep ieee | awk -F'"' '$0=$2')
#	SSID=$(ifconfig | grep ieee | awk '/join/ {print $3}')
	INTIP=$(ifconfig trunk0 | grep inet | awk '{print $2}')
	IP=$(dig +short myip.opendns.com @resolver1.opendns.com | awk {'printf $1'})
	printf "  $DATE ${pipe} ${gre}CPU:${rst} $CPU_SPEED ($CPU_TEMP°) ${pipe} ${gre}Free Ram:${rst} $RAM "
	printf "${pipe} ${gre}Bat:${rst} $BAT - $BAT_STATUS ${pipe} ${gre}SSID:${rst} $SSID ${pipe}"
	printf " ${gre}Pub. IP:${rst} $IP - ${gre}Int. IP:${rst} $INTIP \r"
	sleep 15
done
